src/Entity/Plant.php
<?php
namespace App\Entity;

use App\Repository\PlantRepository;
use Doctrine\ORM\Mapping as ORM;
use DateTime;

#[ORM\Entity(repositoryClass: PlantRepository::class)]
class Plant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $latin_name = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $type = null;

    #[ORM\Column(type: 'text')]
    private ?string $description = null;

    #[ORM\Column(type: 'string', length: 50)]
    private ?string $size = null;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?DateTime $floweringDate = null;

    #[ORM\Column(type: 'datetime')]
    private ?DateTime $createdDate = null;

    #[ORM\Column(type: 'datetime')]
    private ?DateTime $updatedDate = null;
    
    #[ORM\Column(type:"string", length: 255, nullable:true)]
    private ?string $image = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $slug = null;

    public function __construct()
    {
        $this->createdDate = new DateTime('now');
        $this->updatedDate = new DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLatinName(): ?string
    {
        return $this->latin_name;
    }

    public function setLatinName(string $latin_name): self
    {
        $this->latin_name = $latin_name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(string $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getFloweringDate(): ?DateTime
    {
        return $this->floweringDate;
    }

    public function setFloweringDate(?DateTime $floweringDate): self
    {
        $this->floweringDate = $floweringDate;

        return $this;
    }

    public function getCreatedDate(): ?DateTime
    {
        return $this->createdDate;
    }

    public function setCreatedDate(DateTime $createdDate): self
    {
        $this->createdDate = $createdDate;

        return $this;
    }

    public function getUpdatedDate(): ?DateTime
    {
        return $this->updatedDate;
    }

    public function setUpdatedDate(DateTime $updatedDate): self
    {
        $this->updatedDate = $updatedDate;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Form/PlantType.php
<?php
namespace App\Form;

use App\Entity\Plant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\String\Slugger\AsciiSlugger;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class PlantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom de la plante'
            ])
            ->add('latin_name', TextType::class, [
                'label' => 'Nom latin'
            ])
            ->add('type', TextType::class, [
                'label' => 'Type'
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description'
            ])
            ->add('size', TextType::class, [
                'label' => 'Taille'
            ])
            ->add('floweringDate', DateTimeType::class, [
                'label' => 'Date de floraison',
                'widget' => 'single_text',
                'required' => false
            ])
            ->add('image', FileType::class, [
                'label' => 'Image',
                'required' => false,
                'mapped' => false,
                'attr' => ['accept' => 'image/*']
            ])
            // ->add('save', SubmitType::class, [
            //     'label' => 'Ajouter'
            // ])
            ->addEventListener(FormEvents::POST_SUBMIT, [$this, 'onPostSubmit']);
    }


    public function onPostSubmit(FormEvent $event)
    {
        $plant = $event->getData();
        
        if (!$plant instanceof Plant) {
            return;
        }
        
        $slugger = new AsciiSlugger();
        $name = $plant->getName();
        if ($name) {
            $slug = $slugger->slug($name);
            $plant->setSlug($slug);
        }
        
        if ($plant->getCreatedDate() === null) {
            $plant->setCreatedDate(new \DateTime('now'));
        }
        
        $plant->setUpdatedDate(new \DateTime('now'));
    }

    
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Plant::class,
        ]);
    }
}

src/Controller/PlantController.php
<?php

namespace App\Controller;

use App\Entity\Plant;
use App\Form\PlantType;
use App\Repository\PlantRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\String\Slugger\AsciiSlugger;


class PlantController extends AbstractController
{

    #[Route('/')] 
    public function redirection(): Response 
    {
        return $this->redirectToRoute('plant_list');
    }

    #[Route('/plants', name: 'plant_list')]
    public function list(Request $request, PlantRepository $plantRepository, PaginatorInterface $paginator): Response
    {
        $queryBuilder = $plantRepository->createQueryBuilder('p');
        
        
        $pagination = $paginator->paginate(
            $queryBuilder, 
            $request->query->getInt('page', 1), 
            10 
        );

        return $this->render('plant/list.html.twig', [
            'pagination' => $pagination,
        ]);
    }

    

    #[Route('/plant/{slug}-{id}', name: 'plant_detail', requirements: ['id' => '\d+', 'slug' => '[a-zA-Z0-9\-]+'])]
    public function detail(string $slug, int $id, PlantRepository $plantRepository): Response
    {
        $plant = $plantRepository->find($id);
    
        if (!$plant || $plant->getSlug() !== $slug) {
            throw $this->createNotFoundException('Plante non trouvée');
        }
    
        return $this->render('plant/detail.html.twig', [
            'plant' => $plant,
        ]);
    }

    
    #[Route('/plant/add', name: 'plant_add')]
    public function add(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $plant = new Plant();
        $form = $this->createForm(PlantType::class, $plant);

        $request->setLocale('fr');
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $plant->setCreatedDate(new \DateTime('now'));
            $plant->setUpdatedDate(new \DateTime('now'));

            $uploadedFile = $form->get('image')->getData();
            if ($uploadedFile) {
                $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$uploadedFile->guessExtension();

                $destination = $this->getParameter('kernel.project_dir').'/public/uploads/images';
                $uploadedFile->move($destination, $newFilename);

                $plant->setImage($newFilename);
            }

            $entityManager->persist($plant);
            $entityManager->flush();

            return $this->redirectToRoute('plant_list');
        }

        return $this->render('plant/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/plant/edit/{id}', name: 'plant_edit', requirements: ['id' => '\d+'])]
    public function edit(Request $request, Plant $plant, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PlantType::class, $plant);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            

            $file = $form->get('image')->getData();
            if ($file) {
                $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                $newFilename = $originalFilename.'-'.uniqid().'.'.$file->guessExtension();

                $file->move(
                    $this->getParameter('kernel.project_dir').'/public/uploads/images',
                    $newFilename
                );

                $plant->setImage($newFilename);
            }

            $plant->setUpdatedDate(new \DateTime('now'));

            $entityManager->flush();

            return $this->redirectToRoute('plant_list');
        }

        return $this->render('plant/edit.html.twig', [
            'form' => $form->createView(),
            'plant' => $plant,
        ]);
    }


    #[Route('/plant/delete/{id}', name: 'plant_delete', requirements: ['id' => '\d+'])]
    public function delete(Request $request, Plant $plant, EntityManagerInterface $entityManager): Response
    {
            $entityManager->remove($plant);
            $entityManager->flush();
        

        return $this->redirectToRoute('plant_list');
    }
}

templates/plant/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une plante{% endblock %}

{% block body %}
    <h1>Ajouter une nouvelle plante</h1>

        {% if app.user %}

    {{ form_start(form, {'attr': {'enctype': 'multipart/form-data'}}) }}
        {{ form_widget(form) }}
                <button class="btn">Ajouter</button>

    {{ form_end(form) }}

    {% else %}
    <h2>Vous devez être connectés</h2>
    {% endif %}
{% endblock %}

templates/plant/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails de la Plante{% endblock %}

{% block body %}
    <h1>Détails de la Plante</h1>
<div class="plant-detail" style='background-image: url("{{ asset('uploads/images/' ~ (plant.getImage ? plant.getImage : 'default.jpg')) }}");'>
<span>{{ plant.getName }}</span></div>


    <table>
        <tr>
            <th colspan='2'>Nom Latin</th>
            <td colspan='2'>{{ plant.getLatinName }}</td>
        </tr>
        <tr>
            <th colspan='2'>Type</th>
            <td colspan='2'>{{ plant.getType }}</td>
        </tr>
<tr>
    <th colspan='2'>Date de floraison</th>
    <td colspan='2'>{{ plant.getFloweringDate ? plant.getFloweringDate|date('d/m/Y') : 'Non spécifié' }}</td>
</tr>

        <tr>
            <th colspan='2'>Description</th>
            <td colspan='2'>{{ plant.getDescription }}</td>
        </tr>
        <tr>
            <th  colspan='2'>Taille</th>
            <td  colspan='2'>{{ plant.getSize }}</td>
        </tr>
    </table>
    <table>
        <th>Date d'ajout : {{ plant.getCreatedDate ? plant.getCreatedDate|date('d/m/Y') : 'Non spécifié' }} - Dernière M.A.J : {{ plant.getUpdatedDate ? plant.getUpdatedDate|date('d/m/Y') : 'Non spécifié' }}</th>
    </table>

{% endblock %}

templates/plant/edit.html.twig
{# templates/plant/edit.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Éditer une Plante{% endblock %}

{% block body %}
    <h1>Éditer une Plante</h1>

        {% if app.user %}
    <div class="formulaire">
    {{ form_start(form, { 'attr': { 'enctype': 'multipart/form-data' } }) }}
        {{ form_widget(form) }}

        {% if plant.image %}
            <div class="current-image">
                <h2>Image actuelle</h2>
                <img src="{{ asset('uploads/images/' ~ plant.image) }}" alt="Image de la plante" style="max-width: 200px; height: auto;" />
            </div>
        {% endif %}

        <button class="btn">Enregistrer les modifications</button>
    {{ form_end(form) }}
    </div>
    {% else %}
    <h2>Vous devez être connectés</h2>
    {% endif %}
{% endblock %}

templates/plant/list.html.twig
{# templates/plant/list.html.twig #}
{% extends 'base.html.twig' %}

{% block title %}Liste des Plantes{% endblock %}

{% block body %}
    <h1>Liste des Plantes</h1>

    <div class="plant-list-container">
        <form id="searchForm" class="search-form">
            <input type="text" id="searchName" placeholder="Rechercher par nom de la plante" />
            <button type="button" id="clearButton">Effacer</button> 
        </form>
    </div>

    <div class="plant-list-container">
        <ul class="plant-list" id="plantList">
            {% for plant in pagination %}
                <li class="plant-item" data-name="{{ plant.name }}" data-latin-name="{{ plant.latinName }}" data-type="{{ plant.type }}" data-flowering-date="{{ plant.floweringDate ? plant.floweringDate|date('d/m/Y') : 'Non spécifié' }}">
                    <a href="{{ path('plant_detail', {'slug': plant.slug, 'id': plant.id}) }}">{{ plant.name }}</a>
                    {% if app.user %}
                    <div class="actions">
                        <a class="edit-link" href="{{ path('plant_edit', { id: plant.id }) }}">Éditer</a>
                    <form method="post" action="{{ path('plant_delete', { id: plant.id }) }}" style="margin-top:0;" id="delete-form-{{ plant.id }}" data-confirm="Êtes-vous sûr de vouloir supprimer cette plante ?">
                        <button class="btn btn-link" type="submit">Supprimer</button>
                    </form>
                    </div>
                    {% else %}
                    <div class="actions">
                        <a>Vous devez être connectés</a>
                    </div>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="pagination">
        {% if pagination.currentPageNumber > 1 %}
            <a href="{{ path('plant_list', { page: pagination.currentPageNumber - 1 }) }}">Précédent</a>
        {% else %}
            <span>Précédent</span>
        {% endif %}

        <span>Page {{ pagination.currentPageNumber }} sur {{ pagination.pageCount }}</span>

        {% if pagination.currentPageNumber < pagination.pageCount %}
            <a href="{{ path('plant_list', { page: pagination.currentPageNumber + 1 }) }}">Suivant</a>
        {% else %}
            <span>Suivant</span>
        {% endif %}
    </div>


    <script src="{{ asset('js/confirmation.js') }}"></script>
    <script src="{{ asset('js/filter.js') }}"></script>
{% endblock %}